name: shapee_project
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^3.0.8
  dio_http_cache: ^0.2.1
  provider: ^4.0.0
  intl: ^0.16.1
  rxdart: ^0.23.1
  keyboard_dismisser: ^1.0.2
  keyboard_visibility: ^0.5.2
  get_it: ^4.0.1
  after_layout: ^1.0.7+2
  shared_preferences: ^0.5.12+2
  cupertino_icons: ^1.0.0
  dots_indicator: ^1.2.0
  get: ^3.15.0
  pin_code_fields: ^6.0.1
  flutter_datetime_picker: ^1.4.0
  flutter_svg: ^0.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"
  build_runner: ^1.8.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - lib/localization/lang/en.json

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Italic.ttf
          style: italic
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700